### ISSUE TITLE
Java error for rf2 to owl conversion (Java 17 InaccessibleObjectException)

### ISSUE THREAD

**Issue by ManuelFreudenreich** [IHTSDO/snomed-owl-toolkit#63]
Hi,
my girlfriend needs to convert data from rf2 to the owl format. Because she is not that advanced with programming I tried to help her with this task.
The problem is I followed the readme and did the following things:
- Downloaded the newest data zip-file SnomedCT_InternationalRF2_PRODUCTION_20220228T120000Z.zip from the official snomed website.
- I downloaded the executable version 3.0.6.
- I run following command: java -Xms4g -jar .\snomed-owl-toolkit-3.0.6-executable.jar -rf2-to-owl -rf2-snapshot-archives C:\Users\HD-Container\Desktop\SnomedCT_InternationalRF2_PRODUCTION_20220228T120000Z.zip -version 20220228

The problem is now that the output is as following:

java -Xms4g -jar .\snomed-owl-toolkit-3.0.6-executable.jar -rf2-to-owl -rf2-snapshot-archives C:\Users\HD-Container\Desktop\SnomedCT_InternationalRF2_PRODUCTION_20220228T120000Z.zip -version 20220228
Creating Ontology using the following options:
  Snapshot archives: [C:\Users\HD-Container\Desktop\SnomedCT_InternationalRF2_PRODUCTION_20220228T120000Z.zip]
  Delta archive: -none-
  Ontology URI: http://snomed.info/sct/900000000000207008
  Ontology Version: 20220228
  Include Description Annotations: true
2022-03-30 17:18:59,372 [INFO  ] [main] org.snomed.otf.owltoolkit.conversion.RF2ToOWLService - Loading RF2 files
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.ExceptionInInitializerError
        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:72)
        at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:216)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:64)
        at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:204)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.<init>(ProviderMethod.java:256)
        at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:71)
        at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:275)
        at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:144)
        at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:349)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:89)
        at org.semanticweb.owlapi.apibinding.OWLManager.instatiateOWLOntologyManager(OWLManager.java:97)
        at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:58)
        at org.snomed.otf.owltoolkit.taxonomy.AxiomDeserialiser.<init>(AxiomDeserialiser.java:33)
        at org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyLoader.<init>(SnomedTaxonomyLoader.java:55)
        at org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyLoader.<init>(SnomedTaxonomyLoader.java:64)
        at org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder.build(SnomedTaxonomyBuilder.java:118)
        at org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder.build(SnomedTaxonomyBuilder.java:82)
        at org.snomed.otf.owltoolkit.conversion.RF2ToOWLService.convertRF2ArchiveToOWL(RF2ToOWLService.java:45)
        at org.snomed.otf.owltoolkit.Application.rf2ToOwl(Application.java:145)
        at org.snomed.otf.owltoolkit.Application.run(Application.java:88)
        at org.snomed.otf.owltoolkit.Application.main(Application.java:53)
        ... 8 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @59a6e353
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.google.inject.internal.cglib.core.$ReflectUtils$2.run(ReflectUtils.java:56)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:46)
        ... 39 more

I am not that advanced in java and I was not able to find a solution online. Maybe its because of the java-Version installed:
java --version
java 17.0.2 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)

Please let me know if I did something wrong there or if you have an idea what the problem could be.

Thank you in advance and best regards
Manuel Freudenreich

**Comment by kaicode** [comment]
Hi @ManuelFreudenreich, 

I'm sorry the RF2 to OWL file conversion is not working for you. It looks like you followed the instructions perfectly.
This appears to be a new restriction in Java 17 to do with how classes use other classes within a java application. For now please follow a [workaround](https://stackoverflow.com/a/68168810) by adding the command line java parameter:
```--add-opens java.base/java.lang=ALL-UNNAMED```

So your complete command would now be:
```
java --add-opens java.base/java.lang=ALL-UNNAMED -Xms4g -jar .\snomed-owl-toolkit-3.0.6-executable.jar -rf2-to-owl -rf2-snapshot-archives C:\Users\HD-Container\Desktop\SnomedCT_InternationalRF2_PRODUCTION_20220228T120000Z.zip -version 20220228
```

I hope that workaround solves the issue for you. We will look for a longer term fix for this in a future release of the snomed-owl-toolkit.

Kind regards.

**Comment by kaicode** [comment]
For the record - I think this will be fixed when #61 is included in the release. We should test it on Java 17!

**Comment by kaicode** [comment]
Good luck on Java 17. Let us know how it goes.
We know it works on Java 11 if it doesn't work out.

**Comment by ManuelFreudenreich** [comment]
It worked with the additional java parameter on Java 17.

Thanks again for the fast help.

This can be closed from my side.

**Comment by kaicode** [comment]
Great news, thanks @ManuelFreudenreich

**Comment by kaicode** [comment]
Actually, I'll leave it open until it's fixed in a release. Cheers.

**Comment by spiros** [comment]
A quick note to say the additional parameter also worked on Java `18.0.2`, thanks @kaicode

**Comment by kaicode** [comment]
Thanks for letting us know @spiros 👍

**Comment by mbampi** [comment]
Thanks @kaicode 
Just contributing that the problem still occurring and that on the environment of a M1 Mac with `20.0.1` openjdk version the flags provided fix the problem:
```
java --version

openjdk 20.0.1 2023-04-18
OpenJDK Runtime Environment Homebrew (build 20.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 20.0.1, mixed mode, sharing)
```

I suggest that if the problem is not solved in a short term, it would be nice to add this information on the README. 
If that's desired, I can do it.

**Comment by kaicode** [comment]
@mbampi thanks for the information and your recommendation. I have added a section in the readme about java versions and this solution https://github.com/IHTSDO/snomed-owl-toolkit/blob/master/readme.md#command-line-use
